### ISSUE TITLE
Error in my server

### ISSUE THREAD

**Issue by Tobies** [koca2000/NoteBlockAPI#77] opened 2021-03-26 08:34 UTC
[NoteBlockAPI] Task #268313 for NoteBlockAPI v1.5.0 generated an exception
26.03 09:31:53 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: Index -181 out of bounds for length 360
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.utils.MathUtils.stereoPan(MathUtils.java:44) ~[?:?]
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.utils.CompatibilityUtils.playSoundUniversal(CompatibilityUtils.java:196) ~[?:?]
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.utils.CompatibilityUtils.playSound(CompatibilityUtils.java:187) ~[?:?]
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.model.playmode.MonoMode.play(MonoMode.java:22) ~[?:?]
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.songplayer.RadioSongPlayer.playTick(RadioSongPlayer.java:65) ~[?:?]
26.03 09:31:53 [Server] INFO at com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$null$6(SongPlayer.java:405) ~[?:?]
26.03 09:31:53 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1370) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1283) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-960]
26.03 09:31:53 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-960]

I don't really know what caused, The server currently runs with 420~ players and it's the first time I got an error in 3 months of using this API

**Comment by koca2000** [comment] 2021-03-26 11:40
Duplicate of #71

**Closed** 2021-03-26 11:41 UTC
