### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by mibby** [koca2000/NoteBlockAPI#74] opened 2021-02-18 05:09 UTC
NoteBlockAPI dev 30
http://ci.haprosgames.com/job/NoteBlockAPI/

Noticed this error in my logs.
```
[20:10:28] [Server thread/ERROR]: [NoteBlockAPI] Task #1269067 for NoteBlockAPI v1.6.1.1-SNAPSHOT generated an exception
[20:10:29] [Server thread/ERROR]: [NoteBlockAPI] Suspected Plugins: 
[20:10:29] [Server thread/ERROR]: [NoteBlockAPI] 	MusicBox{enabled,ver=2.0.3,path=plugins/MusicBox-2.0.3-all.jar}
[20:10:29] [Server thread/ERROR]: [NoteBlockAPI] 	NoteBlockAPI{enabled,ver=1.6.1.1-SNAPSHOT,path=plugins/NoteBlockAPI-1.6.1.1-SNAPSHOT.jar}
[20:10:29] [Server thread/ERROR]: [NoteBlockAPI] Exception details below: 
java.lang.NullPointerException: null
	at com.xxmicloxx.NoteBlockAPI.songplayer.EntitySongPlayer.playTick(EntitySongPlayer.java:81) ~[?:?]
	at ru.spliterash.musicbox.customPlayers.objects.SpeakerPlayer.playTick(SpeakerPlayer.java:77) ~[?:?]
	at com.xxmicloxx.NoteBlockAPI.songplayer.SongPlayer.lambda$null$7(SongPlayer.java:441) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1386) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:398) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1295) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-pr/upstream-"5e10802"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by koca2000** [comment] 2021-02-22 19:54
Hi @mibby! Has it happened more than once? On what occasion did the error appeared?

**Comment by mibby** [comment] 2021-02-22 23:21
A player was just playing random songs with the MusicBox plugin with Speaker Mode enabled. Checking all my logs for the last 3 weeks, this error only seemed to have occurred the one time, unlike the ``Index out of bounds for length`` exception.

**Comment by koca2000** [comment] 2022-02-17 21:36
The cause of this error is unknown and I was not able to replicate it, so I close it for now. Feel free to reopen the issue if it happens again.

**Closed by koca2000** 2022-02-17 21:36 UTC
